config/routes.rb
TwitterBootstrapDemo::Application.routes.draw do
  resources :meetings
  root :to => 'meetings#index'
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  validates_presence_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/meetings_controller.rb
class MeetingsController < InheritedResources::Base

  def create
    create! { meetings_path }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TwitterBootstrapDemo
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body

    .topbar
      .topbar-inner
        .container
          = link_to 'aarhus.rb', root_path, :class => 'brand'
          %ul.nav
            %li.active= link_to 'Meetings', meetings_path
            %li= link_to 'Members', meetings_path

    .container

      - if flash.present?
        .alert-message.success
          = flash[:notice] if flash[:notice].present?
          %a.close{:href => '#'} x

      = yield

app/views/meetings/index.html.haml
%section
  %h1 Meetings

  %ul
    - for meeting in @meetings do
      %li= link_to meeting.title, meeting, :rel => 'popover', 'data-content' => meeting.agenda, :title => meeting.location

  = link_to 'new meeting', new_meeting_path, :class => 'btn'

app/views/meetings/new.html.haml
%section
  %h1 New Meeting

  = simple_form_for @meeting, :wrapper => :inline do |f|

    = f.input :title, :hint => '"Novembermøde" for example'

    = f.input :agenda, :input_html => { :class => 'span12' }

    = f.input :location

    = f.input :starts_at, :as => :string, :input_html => { :class => 'datepicker' }

    .actions
      = button_tag 'Cancel', :type => :reset, :class => 'btn'
      = f.button :submit, :class => 'primary'